import { useEffect, useRef } from 'react';
import { ZODIAC_GLYPHS, NAKSHATRAS, calculateAspects, formatDistance, destinationZoneFromBearing } from '../lib/astro';
const GOLD='#F4C842', norm=n=>((n%360)+360)%360, rad=d=>d*Math.PI/180;
const ASPECT_STYLE={Conjunction:['rgba(244,200,66,.58)',[]],Sextile:['rgba(94,234,212,.48)',[3,5]],Square:['rgba(248,113,113,.56)',[]],Trine:['rgba(96,165,250,.52)',[]],Quincunx:['rgba(192,132,252,.46)',[4,5]],Opposition:['rgba(251,146,60,.56)',[]]};
export default function ZodiacWheel({chart,planets=[],selectedPlanet,onSelectPlanet,selectedHouse,onSelectHouse,destinationBearing=null,compact=false,overlay=false,radiusMeters=null,distanceUnit='ft'}){
  const ref=useRef(null), size=compact?500:560;
  useEffect(()=>{const c=ref.current;if(!c||!chart)return;const ctx=c.getContext('2d'),W=c.width,H=c.height,cx=W/2,cy=H/2,R=Math.min(W,H)/2-36;ctx.clearRect(0,0,W,H);const rotation=90-chart.asc;const point=(lon,r)=>{const a=rad(norm(lon+rotation)-90);return[cx+r*Math.cos(a),cy+r*Math.sin(a)]};const alpha=overlay?.72:1;
    // outer compass/tick bezel
    ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.strokeStyle=`rgba(244,200,66,${.82*alpha})`;ctx.lineWidth=1.5;ctx.stroke();
    for(let d=0;d<360;d+=2){const major=d%30===0,mid=d%10===0;const ro=R,ri=R-(major?12:mid?7:3);const a=rad(d-90);ctx.beginPath();ctx.moveTo(cx+ri*Math.cos(a),cy+ri*Math.sin(a));ctx.lineTo(cx+ro*Math.cos(a),cy+ro*Math.sin(a));ctx.strokeStyle=`rgba(244,200,66,${(major?.66:mid?.40:.22)*alpha})`;ctx.lineWidth=major?1.1:.55;ctx.stroke()}
    const zodiacOuter=R-15,zodiacInner=R*.83;
    for(let i=0;i<12;i++){const s=rad(i*30+rotation-90),e=rad((i+1)*30+rotation-90);ctx.beginPath();ctx.arc(cx,cy,zodiacOuter,s,e);ctx.arc(cx,cy,zodiacInner,e,s,true);ctx.closePath();ctx.fillStyle=overlay?(i%2?'rgba(6,9,24,.16)':'rgba(6,9,24,.08)'):(i%2?'rgba(12,16,42,.84)':'rgba(7,10,28,.84)');ctx.fill();ctx.strokeStyle=`rgba(244,200,66,${.25*alpha})`;ctx.lineWidth=.7;ctx.stroke();const[x,y]=point(i*30+15,(zodiacOuter+zodiacInner)/2);ctx.font=compact?'13px serif':'17px serif';ctx.fillStyle=`rgba(244,200,66,${.96*alpha})`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(ZODIAC_GLYPHS[i],x,y)}
    const nakOuter=zodiacInner-2,nakInner=R*.655,step=360/27;
    for(let i=0;i<27;i++){const s=rad(i*step+rotation-90),e=rad((i+1)*step+rotation-90);ctx.beginPath();ctx.arc(cx,cy,nakOuter,s,e);ctx.arc(cx,cy,nakInner,e,s,true);ctx.closePath();ctx.fillStyle=overlay?'rgba(8,12,30,.035)':'rgba(255,255,255,.012)';ctx.fill();ctx.strokeStyle=`rgba(218,226,238,${.18*alpha})`;ctx.lineWidth=.48;ctx.stroke();const short=NAKSHATRAS[i].replace('Purva ','P. ').replace('Uttara ','U. ').replace('Bhadrapada','Bhadra').replace('Phalguni','Phalg.').replace('Ashadha','Ash.').slice(0,8);const[x,y]=point(i*step+step/2,(nakOuter+nakInner)/2);ctx.save();ctx.translate(x,y);ctx.rotate(rad(norm(i*step+step/2+rotation)));ctx.font=compact?'6px Inter, sans-serif':'7px Inter, sans-serif';ctx.fillStyle=`rgba(235,239,247,${.86*alpha})`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(short,0,0);ctx.restore()}
    const houseOuter=nakInner-2,houseInner=R*.485,zone=destinationZoneFromBearing(chart,Number(destinationBearing));
    for(let h=0;h<12;h++){const cusp=chart.houseCusps[h],s=rad(cusp+rotation-90),e=rad(cusp+30+rotation-90),active=selectedHouse===h+1||zone?.house===h+1;ctx.beginPath();ctx.arc(cx,cy,houseOuter,s,e);ctx.arc(cx,cy,houseInner,e,s,true);ctx.closePath();ctx.fillStyle=active?`rgba(244,200,66,${overlay?.10:.12})`:overlay?'rgba(8,12,30,.025)':'rgba(255,255,255,.015)';ctx.fill();ctx.strokeStyle=active?`rgba(244,200,66,${.62*alpha})`:`rgba(220,230,241,${.14*alpha})`;ctx.lineWidth=active?1.15:.5;ctx.stroke();const[x,y]=point(cusp+15,(houseOuter+houseInner)/2);ctx.font=compact?'bold 8px Inter':'bold 10px Inter';ctx.fillStyle=active?GOLD:`rgba(235,240,248,${.78*alpha})`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(h+1),x,y)}
    ctx.beginPath();ctx.arc(cx,cy,houseInner-1,0,Math.PI*2);ctx.fillStyle=overlay?'rgba(4,7,20,.035)':'rgba(6,9,26,.90)';ctx.fill();
    const aspectRadius=houseInner-26,byId=new Map(planets.map(p=>[p.id,p]));calculateAspects(planets).forEach(a=>{const pa=byId.get(a.aId),pb=byId.get(a.bId);if(!pa||!pb)return;const[x1,y1]=point(pa.siderealLon,aspectRadius),[x2,y2]=point(pb.siderealLon,aspectRadius),st=ASPECT_STYLE[a.type]||ASPECT_STYLE.Sextile;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=st[0];ctx.globalAlpha=overlay?.78:1;ctx.lineWidth=a.orb<1?1.5:.85;ctx.setLineDash(st[1]);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1});
    const pr=houseInner-13,occupied=[];planets.forEach(p=>{if(!Number.isFinite(p.siderealLon))return;let ring=pr;if(occupied.some(o=>Math.abs(((o-p.siderealLon+540)%360)-180)<4.3))ring-=16;occupied.push(p.siderealLon);const[x,y]=point(p.siderealLon,ring),sel=selectedPlanet?.id===p.id;if(sel){ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fillStyle='rgba(244,200,66,.16)';ctx.fill();ctx.strokeStyle='rgba(244,200,66,.75)';ctx.stroke()}ctx.font=compact?(sel?'16px serif':'13px serif'):(sel?'20px serif':'16px serif');ctx.fillStyle=sel?'#fff7c2':GOLD;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.glyph,x,y)});
    [['N',0],['E',90],['S',180],['W',270]].forEach(([label,d])=>{const a=rad(d-90),rr=R+18,x=cx+rr*Math.cos(a),y=cy+rr*Math.sin(a);ctx.font=label==='E'?'bold 14px Inter':'bold 11px Inter';ctx.fillStyle=label==='E'?'#fff7c2':GOLD;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,x,y)});
    // ASC / destination bearing markers
    const[ax,ay]=point(chart.asc,houseInner-1);ctx.beginPath();ctx.arc(ax,ay,compact?5:6.5,0,Math.PI*2);ctx.fillStyle='#3b82f6';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=1.4;ctx.stroke();
    if(zone){const[dx,dy]=point(zone.longitude,houseInner-1);ctx.beginPath();ctx.arc(dx,dy,compact?5:6.5,0,Math.PI*2);ctx.fillStyle=GOLD;ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(dx,dy);ctx.strokeStyle='rgba(244,200,66,.36)';ctx.setLineDash([4,6]);ctx.stroke();ctx.setLineDash([])}
    if(overlay&&Number.isFinite(radiusMeters)){ctx.font='bold 9px Inter';ctx.fillStyle='rgba(255,255,255,.82)';ctx.textAlign='center';ctx.fillText(`RADIUS ${formatDistance(radiusMeters/1000,distanceUnit).toUpperCase()}`,cx,H-8)}
  },[chart,planets,selectedPlanet,selectedHouse,destinationBearing,compact,overlay,radiusMeters,distanceUnit]);
  const click=e=>{if(!chart)return;const rect=ref.current.getBoundingClientRect(),x=(e.clientX-rect.left)*(ref.current.width/rect.width),y=(e.clientY-rect.top)*(ref.current.height/rect.height),cx=ref.current.width/2,cy=ref.current.height/2,R=Math.min(ref.current.width,ref.current.height)/2-36,dist=Math.hypot(x-cx,y-cy),screen=norm(Math.atan2(y-cy,x-cx)*180/Math.PI+90),lon=norm(screen-(90-chart.asc));if(dist<R*.50){let nearest=null,gap=999;for(const p of planets){const d=Math.abs(((p.siderealLon-lon+540)%360)-180);if(d<gap){gap=d;nearest=p}}if(nearest&&gap<10){onSelectPlanet?.(nearest);return}}if(dist>=R*.485&&dist<=R*.655){const h=Math.floor(norm(lon-chart.asc)/30)+1;onSelectHouse?.(h)}};
  return <div className={overlay?'clean-wheel overlay-wheel':'clean-wheel'}><canvas ref={ref} width={size} height={size} onClick={click} className={compact?'wheel-canvas compact':'wheel-canvas'} aria-label="Interactive sidereal compass. Click a planet glyph or house sector to read its prediction."/>{!compact&&<div className="wheel-key"><span><i className="you-dot"/>ASC / East</span><span><i className="dest-dot"/>Destination bearing</span><span>Click planets or houses for forecasts</span></div>}</div>;
}
