import { FALLBACK_VOCABULARY } from './_private/vocabulary.js';
const VALID_CATEGORIES=['people','events','qualities','places','objects'];
const HOUSE_THEMES={1:['identity','body','personal direction'],2:['money','speech','resources'],3:['communication','movement','short journeys'],4:['home','property','family foundations'],5:['creativity','romance','study'],6:['work','service','health routines','obstacles'],7:['partners','clients','agreements'],8:['shared resources','secrets','sudden change'],9:['belief','teachers','long journeys','dharma'],10:['career','status','responsibility'],11:['gains','friends','networks','goals'],12:['retreat','expenses','foreign places','release']};
const SIGN_THEMES={Aries:['initiative','speed'],Taurus:['stability','resources'],Gemini:['messages','movement'],Cancer:['home','care'],Leo:['visibility','leadership'],Virgo:['analysis','service'],Libra:['agreement','partnership'],Scorpio:['intensity','transformation'],Sagittarius:['travel','belief'],Capricorn:['duty','structure'],Aquarius:['networks','systems'],Pisces:['imagination','release']};
const ASPECT_TONE={Conjunction:'concentrates',Sextile:'opens an opportunity around',Square:'creates pressure around',Trine:'supports an easier flow around',Quincunx:'requires adjustment around',Opposition:'brings a polarity around'};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function normalizeEntries(v){if(!Array.isArray(v))return[];return v.map(x=>typeof x==='string'?{term:x,weight:.65}:x&&typeof x.term==='string'?{term:x.term.trim(),weight:clamp(Number(x.weight)||.65,0,1)}:null).filter(Boolean)}
function mergeBank(base={},custom={}){const m={};for(const c of VALID_CATEGORIES){const own=normalizeEntries(custom?.[c]);m[c]=own.length?own:normalizeEntries(base?.[c])}return m}
function readVocabulary(){let custom={};try{if(process.env.PLANET_VOCAB_JSON)custom=JSON.parse(process.env.PLANET_VOCAB_JSON)}catch{}const out={};for(const k of new Set([...Object.keys(FALLBACK_VOCABULARY),...Object.keys(custom||{})]))out[k]=mergeBank(FALLBACK_VOCABULARY[k],custom?.[k]);return out}
function seedIndex(seed,n){let h=2166136261;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}return n?(h>>>0)%n:0}
function pick(entries,seed){const list=normalizeEntries(entries).sort((a,b)=>b.weight-a.weight).slice(0,8);return list[seedIndex(seed,list.length)]||null}
function degreeSep(a,b){return Math.abs(((Number(a)-Number(b)+540)%360)-180)}
function planetPrediction(p,body,vocab){const bank=vocab[p.id]||{};const contacts=(body.transitNatalAspects||[]).filter(a=>a.transitId===p.id).sort((a,b)=>a.orb-b.orb);const zone=body.destinationZone||{};const houseContacts=(body.natalHouseAspects||[]).filter(a=>a.transitId===p.id&&a.house===zone.house).sort((a,b)=>a.orb-b.orb);const own=(p.aspects||[])[0];const event=pick(bank.events,`${body.date}|${p.id}|event`),quality=pick(bank.qualities,`${body.date}|${p.id}|quality`),place=pick(bank.places,`${body.date}|${p.id}|place`),object=pick(bank.objects,`${body.date}|${p.id}|object`),person=pick(bank.people,`${body.date}|${p.id}|person`);let parts=[];parts.push(`${p.name} is transiting sidereal ${p.sign} ${Number(p.degree).toFixed(2)}° in ${p.nakshatra} pada ${p.pada}, activating current House ${p.house}.`);if(contacts[0])parts.push(`Its ${contacts[0].type.toLowerCase()} to natal ${contacts[0].natalName} points to a period where ${ASPECT_TONE[contacts[0].type]||'connects'} natal ${contacts[0].natalName} themes.`);if(own)parts.push(`At the same time, its current ${own.type.toLowerCase()} with ${own.with} modifies how that transit is expressed.`);if(zone.house===p.house)parts.push(`Because your destination lies in the current House ${zone.house} compass zone, this planet is directly emphasized along the route.`);else if(houseContacts[0])parts.push(`${p.name} also ${houseContacts[0].type.toLowerCase()}s the natal House ${zone.house} cusp associated with the destination zone.`);const prompts=[event?.term,person&&`an encounter involving ${person.term}`,place&&`a place connected with ${place.term}`,object&&`an object/activity connected with ${object.term}`].filter(Boolean);if(quality)parts.push(`The private interpretation vocabulary emphasizes ${quality.term}.`);if(prompts.length)parts.push(`Possible journey manifestations to watch for include ${prompts.slice(0,3).join(', ')}.`);return parts.join(' ')}
function housePrediction(h,body,vocab){const zone=body.destinationZone||{};const l=(body.houseLords||[]).find(x=>x.house===h);const inHouse=(body.planets||[]).filter(p=>p.house===h);const cuspContacts=(body.natalHouseAspects||[]).filter(a=>a.house===h).sort((a,b)=>a.orb-b.orb);let s=`House ${h} centers on ${(HOUSE_THEMES[h]||[]).join(', ')}.`;if(h===zone.house)s+=` This is the active destination zone for the route, so its topics receive extra weight in the journey interpretation.`;if(l)s+=` In the natal chart this house is ruled by ${l.lordName}, placed in natal House ${l.lordHouse}.`;if(inHouse.length)s+=` Current transits physically occupying this house: ${inHouse.map(p=>p.name).join(', ')}.`;if(cuspContacts.length)s+=` Strong transit contacts to the natal House ${h} cusp include ${cuspContacts.slice(0,3).map(a=>`${a.transitName} ${a.type.toLowerCase()} (${a.orb.toFixed(2)}°)`).join(', ')}.`;return s}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const body=typeof req.body==='string'?JSON.parse(req.body):req.body||{};const planets=Array.isArray(body.planets)?body.planets:[];if(!planets.length)return res.status(400).json({error:'No planetary data supplied'});const vocab=readVocabulary();const zone=body.destinationZone||{};const planetPredictions={};for(const p of planets)planetPredictions[p.id]=planetPrediction(p,body,vocab);const housePredictions={};for(let h=1;h<=12;h++)housePredictions[h]=housePrediction(h,body,vocab);const strongest=(body.transitNatalAspects||[]).slice().sort((a,b)=>a.orb-b.orb).slice(0,3);const zonePlanets=planets.filter(p=>p.house===zone.house);let summary=`The route runs ${Number(body.bearing||0).toFixed(0)}° ${body.direction||''} and lands in current compass House ${zone.house||'—'} (${zone.sign||'—'}). `;if(zonePlanets.length)summary+=`${zonePlanets.map(p=>p.name).join(', ')} ${zonePlanets.length===1?'is':'are'} transiting that destination zone. `;if(strongest.length)summary+=`The closest transit-to-natal contacts are ${strongest.map(a=>`${a.transitName} ${a.type.toLowerCase()} natal ${a.natalName} (${Number(a.orb).toFixed(2)}°)`).join('; ')}. `;summary+=`The detailed planet and house panels combine these natal contacts with current transit aspects, destination-zone activation, sidereal sign/nakshatra placement, and the private keyword layer. These are interpretive forecasts rather than guaranteed events.`;return res.status(200).json({summary,planetPredictions,housePredictions,destinationZone:zone,transitNatalAspects:body.transitNatalAspects||[],modelVersion:'natal-transit-route-3'});}catch(e){return res.status(500).json({error:'Interpretation failed'})}}
